name: BUILD AND DEPLOY
on: 
   push:
   branches: ['main']

jobs:
   build: 
    runs-on: [ubuntu-latest]
    steps: 
     - name: Checkout source
     - uses: actions/checkout@v3
     - name: Login to docker hub 
     - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_HUB_USERNAME }} 
     - name : docker image build
     - run : docker build -t nestJs/node-js-app .
     - name: Publish image to docker hub 
    - run: docker push nestJs/node-js-app:latest  
  
 