name: BUILD AND DEPLOY
on: 
   push:
     branches: ['main']

jobs:
   build: 
    runs-on: [ubuntu-latest]
    steps: 
     - name: Checkout source
       uses: actions/checkout@v3
     - name: Login to docker hub 
       env:
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
     - name : docker image build
       run : docker build -t nestJs/node-js-app .
     - name: Publish image to docker hub 
       run: docker push nestJs/node-js-app:latest  
  
 