name: RUN TEST CASE

on :
   pull_request:
   branches: ['main']   


jobs:
   test_on_Pr:
      run-on: [ubuntu-latest]
   step : 
      - name: 'checkout code'
      - uses: actions/checkout@v3
      - name: "build docker file and run test case"
      - run : docker build test.dockerfile -t nest-js-test . 
      - name: "run docker file "
      - run : docker run nest-js-test 
                 
