name: RUN TEST CASE

on :
   pull_request:
      branches: ['main']   


jobs:
   test_on_Pr:
       runs-on: [ubuntu-latest]
       steps: 
         - name: checkout code
           uses: actions/checkout@v3
         - name: build docker file and run test case 
           run: docker build -t nest-js-test -f test.dockerfile .
         - name : run docker file
           run : docker run nest-js-test
                 


 

 